/**
 * build-vs-frame.ts
 * Reads public/vs/{components.css, helper.js, frame.html},
 * inlines CSS+JS into the frame template, and outputs
 * src/lib/vs-frame.ts as an exported string constant.
 *
 * Usage: npx tsx scripts/build-vs-frame.ts
 */
import * as fs from "fs";
import * as path from "path";

const root = path.resolve(__dirname, "..");
const vsDir = path.join(root, "public", "vs");

const css = fs.readFileSync(path.join(vsDir, "components.css"), "utf-8");
const js = fs.readFileSync(path.join(vsDir, "helper.js"), "utf-8");
const frame = fs.readFileSync(path.join(vsDir, "frame.html"), "utf-8");

const result = frame
  .replace("/* components.css inlined here */", css)
  .replace("/* helper.js inlined here */", js);

const output = [
  "// Auto-generated by scripts/build-vs-frame.ts — do not edit",
  `export const VS_FRAME_TEMPLATE = ${JSON.stringify(result)};`,
  "",
].join("\n");

const outPath = path.join(root, "src", "lib", "vs-frame.ts");
fs.writeFileSync(outPath, output);

const sizeKB = (Buffer.byteLength(output) / 1024).toFixed(1);
console.log(`[build-vs-frame] wrote ${outPath} (${sizeKB} KB)`);
